baseURL = "https://hassen.io/"
languageCode = "en-us"
title = "Hassen Taidirt"
theme = ["github.com/nodejh/hugo-theme-mini"]
googleAnalytics = "G-CBM4L789H1"
defaultContentLanguage = "en"
paginate = 3

[params]
  author = "Hassen Taidirt"
  bio = "Developer, DevOps and Data aficionado"
  enableGoogleAnalytics = true
  enableRSS = true
  showToc = true

[social]
  github = "https://github.com/HassenIO"
  twitter = "https://twitter.com/htaidirt"
  stackoverflow = "https://stackoverflow.com/users/1201298/hassen"
